# Generated by Django 2.2.dev20180727211500 on 2018-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarManagment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='mileage_data',
            field=models.DateField(default=0),
        ),
    ]
